version: "3.6"

services:
  django:
    image: python:3.8.9
    entrypoint: ["/doplat/entrypoint.sh"]
    volumes:
      - /data/doplat:/doplat
    ports:
      - "2080:8000"

  nginx:
    image: nginx:1.19.10
    volumes:
      - ./nginx-vhost.conf:/etc/nginx/conf.d/nginx-vhost.conf
      - /data/doplat:/doplat
    ports:
      - "80:90"
