# Generated by Django 3.1.13 on 2021-08-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('url', models.CharField(max_length=255, verbose_name='地址')),
                ('img', models.CharField(help_text='例如: /images/abc.jpg', max_length=255, null=True, verbose_name='图片')),
                ('order', models.IntegerField(default=100, verbose_name='排序')),
            ],
            options={
                'verbose_name': '首页地址',
                'verbose_name_plural': '首页地址',
                'ordering': ['order'],
            },
        ),
    ]
