# Generated by Django 3.1.13 on 2021-08-14 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['name'], 'verbose_name': '账号', 'verbose_name_plural': '账号'},
        ),
    ]
