# Generated by Django 3.1.13 on 2021-08-12 06:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='名称')),
                ('username', models.CharField(max_length=200, verbose_name='用户名')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
                ('addr', models.CharField(blank=True, max_length=200, null=True, verbose_name='地址')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Env',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('alias', models.CharField(blank=True, max_length=200, verbose_name='简称')),
            ],
            options={
                'verbose_name': '环境',
                'verbose_name_plural': '环境',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='显示名称')),
                ('hostname', models.CharField(blank=True, max_length=200, verbose_name='主机名')),
                ('inside_ip', models.GenericIPAddressField(verbose_name='内网 IP')),
                ('outside_ip', models.GenericIPAddressField(default='0.0.0.0', verbose_name='外网 IP')),
                ('inside_port', models.IntegerField(default=22, verbose_name='内网端口号')),
                ('outside_port', models.IntegerField(default=52113, verbose_name='外网端口号')),
                ('os', models.CharField(max_length=200, verbose_name='系统')),
                ('cpu', models.IntegerField(default=4, verbose_name='CPU 核数')),
                ('memory', models.CharField(default='8G', max_length=10, verbose_name='内存大小')),
                ('disk', models.CharField(default='80G', max_length=10, verbose_name='硬盘大小')),
                ('cloud', models.CharField(max_length=200, verbose_name='云平台')),
                ('cloud_user', models.CharField(blank=True, max_length=200, verbose_name='云账号')),
                ('env', models.CharField(default='test', max_length=200, verbose_name='环境')),
                ('user', models.CharField(default='root', max_length=200, verbose_name='用户')),
                ('password', models.CharField(default='123456', max_length=200, verbose_name='密码')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '主机',
                'verbose_name_plural': '主机',
                'ordering': ['cloud_user', 'env', 'hostname', 'inside_ip'],
                'unique_together': {('inside_ip', 'cloud_user')},
            },
        ),
        migrations.CreateModel(
            name='MySQL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inside_addr', models.CharField(max_length=200, unique=True, verbose_name='内网地址')),
                ('outside_addr', models.CharField(blank=True, max_length=200, verbose_name='外网地址')),
                ('role', models.CharField(max_length=200, verbose_name='角色')),
                ('data_dir', models.CharField(blank=True, max_length=200, verbose_name='数据库路径')),
                ('version', models.CharField(max_length=200, verbose_name='版本号')),
                ('manager', models.CharField(max_length=200, verbose_name='管理员')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
                ('method', models.CharField(default='normal', max_length=200, verbose_name='部署方式')),
                ('origin', models.CharField(default='自建', max_length=200, verbose_name='来源')),
                ('cluster', models.CharField(blank=True, max_length=200, verbose_name='集群')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='名称')),
                ('alias', models.CharField(blank=True, max_length=200, verbose_name='简称')),
                ('deploy_dir', models.CharField(blank=True, max_length=200, verbose_name='部署路径')),
                ('user', models.CharField(default='www', max_length=200, verbose_name='管理用户')),
                ('log_dir', models.CharField(blank=True, max_length=200, verbose_name='日志路径')),
                ('used', models.BooleanField(default=True, verbose_name='使用中')),
                ('hosts', models.ManyToManyField(blank=True, related_name='project', to='project.Host', verbose_name='主机')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('url', models.URLField(unique=True, verbose_name='地址')),
                ('popular', models.BooleanField(default=False, verbose_name='常用的')),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.env', verbose_name='环境')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='urls', to='project.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '地址大全',
                'verbose_name_plural': '地址大全',
                'ordering': ['project', 'env', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=255, verbose_name='模块名')),
                ('pkg_name', models.CharField(blank=True, max_length=255, verbose_name='包名')),
                ('pkg_type', models.CharField(blank=True, choices=[('jar', 'jar'), ('war', 'war')], max_length=255, verbose_name='包类型')),
                ('port', models.IntegerField(blank=True, verbose_name='端口号')),
                ('deploy_dir', models.CharField(blank=True, max_length=255, verbose_name='部署路径')),
                ('logfile', models.CharField(blank=True, max_length=255, verbose_name='日志文件')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modules', to='project.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目模块',
                'verbose_name_plural': '项目模块',
                'ordering': ['project', 'pkg_type', 'module'],
                'unique_together': {('project', 'module')},
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conf', models.TextField(verbose_name='配置')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.env', verbose_name='环境')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.project', verbose_name='项目')),
            ],
            options={
                'ordering': ['project'],
                'unique_together': {('project', 'env')},
            },
        ),
        migrations.CreateModel(
            name='BuildHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='www', max_length=200, verbose_name='打包用户')),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.env', verbose_name='环境')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.host', verbose_name='主机')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '打包主机',
                'verbose_name_plural': '打包主机',
                'unique_together': {('project', 'env')},
            },
        ),
    ]
