# Generated by Django 3.1.13 on 2021-08-14 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_delete_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'ordering': ['project'], 'verbose_name': '配置', 'verbose_name_plural': '配置'},
        ),
        migrations.AlterModelOptions(
            name='mysql',
            options={'ordering': ['cluster', 'inside_addr'], 'verbose_name': 'MySQL', 'verbose_name_plural': 'MySQL'},
        ),
    ]
