# Generated by Django 3.1.13 on 2021-08-23 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20210814_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Middleware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conn_addr', models.CharField(max_length=200, unique=True, verbose_name='连接地址')),
                ('web_addr', models.CharField(blank=True, max_length=200, verbose_name='Web 地址')),
                ('username', models.CharField(blank=True, max_length=200, verbose_name='用户名')),
                ('password', models.CharField(blank=True, max_length=200, verbose_name='密码')),
                ('type', models.CharField(max_length=200, verbose_name='类别')),
                ('cluster', models.CharField(default='单节点', max_length=200, verbose_name='集群名')),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.env', verbose_name='环境')),
                ('project', models.ManyToManyField(to='project.Project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '中间件',
                'verbose_name_plural': '中间件',
                'ordering': ['env', 'cluster', 'conn_addr'],
            },
        ),
    ]
