# Generated by Django 3.1.13 on 2021-08-23 06:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_middleware'),
    ]

    operations = [
        migrations.AddField(
            model_name='middleware',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
    ]
