# Generated by Django 3.1.13 on 2021-09-10 06:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20210824_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenkinsJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='名称')),
                ('url', models.CharField(max_length=255, verbose_name='地址')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='创建时间')),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.env', verbose_name='环境')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.project', verbose_name='项目')),
            ],
            options={
                'ordering': ['project', 'env', 'name'],
            },
        ),
    ]
