# Generated by Django 3.1.13 on 2021-09-10 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20210910_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jenkinsjob',
            name='created',
        ),
        migrations.AddField(
            model_name='jenkinsjob',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='创建时间'),
        ),
    ]
