# Generated by Django 3.1.13 on 2021-09-11 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20210910_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='jenkinsjob',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='jenkinsjob',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jenkinsjobs', to='project.project', verbose_name='项目'),
        ),
    ]
