# Generated by Django 3.1.13 on 2021-09-14 06:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20210911_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='创建时间'),
        ),
    ]
