# Generated by Django 3.1.13 on 2021-09-15 02:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20210914_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitlabRepo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('http_url_to_repo', models.URLField(verbose_name='地址')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='创建时间')),
                ('last_activity_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='创建时间')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gitlabrepo', to='project.project', verbose_name='项目')),
            ],
            options={
                'ordering': ['project', 'name'],
            },
        ),
    ]
