# Generated by Django 3.1.13 on 2021-09-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_gitlabrepo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gitlabrepo',
            options={'ordering': ['http_url_to_repo', 'project', 'path_with_namespace']},
        ),
        migrations.RemoveField(
            model_name='gitlabrepo',
            name='name',
        ),
        migrations.AddField(
            model_name='gitlabrepo',
            name='path_with_namespace',
            field=models.CharField(default='a', max_length=255, verbose_name='路径'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gitlabrepo',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
