# Generated by Django 3.1.13 on 2021-09-15 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_auto_20210915_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gitlabrepo',
            options={'ordering': ['project', 'path_with_namespace']},
        ),
        migrations.AddField(
            model_name='gitlabrepo',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='gitlabrepo',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gitlabrepos', to='project.project', verbose_name='项目'),
        ),
    ]
