# Generated by Django 3.1.13 on 2021-10-16 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_auto_20210915_2021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='middleware',
            options={'verbose_name': '中间件', 'verbose_name_plural': '中间件'},
        ),
        migrations.AddField(
            model_name='url',
            name='alias',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='简称'),
        ),
        migrations.AddField(
            model_name='url',
            name='deploy_dir',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='部署路径'),
        ),
        migrations.AddField(
            model_name='url',
            name='hosts',
            field=models.ManyToManyField(blank=True, related_name='host_url', to='project.Host', verbose_name='主机'),
        ),
    ]
