# Generated by Django 3.1.13 on 2021-10-16 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_auto_20211016_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='public_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='公网 IP'),
        ),
    ]
