# Generated by Django 3.1.13 on 2021-10-22 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_mysql_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysql',
            name='env',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='project.env', verbose_name='环境'),
        ),
    ]
