# Generated by Django 3.1.13 on 2021-08-14 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('authperm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='l2menu',
            name='is_model',
        ),
        migrations.RemoveField(
            model_name='l2menu',
            name='name',
        ),
        migrations.AddField(
            model_name='l2menu',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='绑定模型', limit_choices_to={'app_label__in': ['app', 'authperm', 'project']}, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='模型'),
        ),
    ]
