# Generated by Django 3.1.13 on 2021-08-24 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authperm', '0002_auto_20210814_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='l2menu',
            options={'ordering': ['parent', 'order', 'component'], 'verbose_name': '二级菜单', 'verbose_name_plural': '二级菜单'},
        ),
    ]
